// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void FinishSplitAnimationHandler(ReducerEventContext ctx, int entityId);
        public event FinishSplitAnimationHandler? OnFinishSplitAnimation;

        public void FinishSplitAnimation(int entityId)
        {
            conn.InternalCallReducer(new Reducer.FinishSplitAnimation(entityId));
        }

        public bool InvokeFinishSplitAnimation(ReducerEventContext ctx, Reducer.FinishSplitAnimation args)
        {
            if (OnFinishSplitAnimation == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnFinishSplitAnimation(
                ctx,
                args.EntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class FinishSplitAnimation : Reducer, IReducerArgs
        {
            [DataMember(Name = "entity_id")]
            public int EntityId;

            public FinishSplitAnimation(int EntityId)
            {
                this.EntityId = EntityId;
            }

            public FinishSplitAnimation()
            {
            }

            string IReducerArgs.ReducerName => "FinishSplitAnimation";
        }
    }
}
