// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ShootBulletHandler(ReducerEventContext ctx, float targetX, float targetY, int bulletType);
        public event ShootBulletHandler? OnShootBullet;

        public void ShootBullet(float targetX, float targetY, int bulletType)
        {
            conn.InternalCallReducer(new Reducer.ShootBullet(targetX, targetY, bulletType));
        }

        public bool InvokeShootBullet(ReducerEventContext ctx, Reducer.ShootBullet args)
        {
            if (OnShootBullet == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnShootBullet(
                ctx,
                args.TargetX,
                args.TargetY,
                args.BulletType
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ShootBullet : Reducer, IReducerArgs
        {
            [DataMember(Name = "target_x")]
            public float TargetX;
            [DataMember(Name = "target_y")]
            public float TargetY;
            [DataMember(Name = "bullet_type")]
            public int BulletType;

            public ShootBullet(
                float TargetX,
                float TargetY,
                int BulletType
            )
            {
                this.TargetX = TargetX;
                this.TargetY = TargetY;
                this.BulletType = BulletType;
            }

            public ShootBullet()
            {
            }

            string IReducerArgs.ReducerName => "ShootBullet";
        }
    }
}
