// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdatePlayerDirHandler(ReducerEventContext ctx, SpacetimeDB.Types.DbVector2 dir);
        public event UpdatePlayerDirHandler? OnUpdatePlayerDir;

        public void UpdatePlayerDir(SpacetimeDB.Types.DbVector2 dir)
        {
            conn.InternalCallReducer(new Reducer.UpdatePlayerDir(dir));
        }

        public bool InvokeUpdatePlayerDir(ReducerEventContext ctx, Reducer.UpdatePlayerDir args)
        {
            if (OnUpdatePlayerDir == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdatePlayerDir(
                ctx,
                args.Dir
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdatePlayerDir : Reducer, IReducerArgs
        {
            [DataMember(Name = "dir")]
            public DbVector2 Dir;

            public UpdatePlayerDir(DbVector2 Dir)
            {
                this.Dir = Dir;
            }

            public UpdatePlayerDir()
            {
                this.Dir = new();
            }

            string IReducerArgs.ReducerName => "UpdatePlayerDir";
        }
    }
}
