// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Bullet
    {
        [DataMember(Name = "entity_id")]
        public int EntityId;
        [DataMember(Name = "owner_player_id")]
        public int OwnerPlayerId;
        [DataMember(Name = "dir_x")]
        public float DirX;
        [DataMember(Name = "dir_y")]
        public float DirY;
        [DataMember(Name = "spawned_at_ms")]
        public double SpawnedAtMs;
        [DataMember(Name = "bullet_type")]
        public int BulletType;

        public Bullet(
            int EntityId,
            int OwnerPlayerId,
            float DirX,
            float DirY,
            double SpawnedAtMs,
            int BulletType
        )
        {
            this.EntityId = EntityId;
            this.OwnerPlayerId = OwnerPlayerId;
            this.DirX = DirX;
            this.DirY = DirY;
            this.SpawnedAtMs = SpawnedAtMs;
            this.BulletType = BulletType;
        }

        public Bullet()
        {
        }
    }
}
