// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Circle
    {
        [DataMember(Name = "entity_id")]
        public int EntityId;
        [DataMember(Name = "player_id")]
        public int PlayerId;
        [DataMember(Name = "touchStartMs")]
        public double TouchStartMs;
        [DataMember(Name = "isMerging")]
        public bool IsMerging;
        [DataMember(Name = "isSplitting")]
        public bool IsSplitting;
        [DataMember(Name = "splitFromEntityId")]
        public int SplitFromEntityId;

        public Circle(
            int EntityId,
            int PlayerId,
            double TouchStartMs,
            bool IsMerging,
            bool IsSplitting,
            int SplitFromEntityId
        )
        {
            this.EntityId = EntityId;
            this.PlayerId = PlayerId;
            this.TouchStartMs = TouchStartMs;
            this.IsMerging = IsMerging;
            this.IsSplitting = IsSplitting;
            this.SplitFromEntityId = SplitFromEntityId;
        }

        public Circle()
        {
        }
    }
}
