// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Entity
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "mass")]
        public float Mass;
        [DataMember(Name = "position")]
        public DbVector2 Position;
        [DataMember(Name = "hp")]
        public float Hp;
        [DataMember(Name = "max_hp")]
        public float MaxHp;

        public Entity(
            int Id,
            float Mass,
            DbVector2 Position,
            float Hp,
            float MaxHp
        )
        {
            this.Id = Id;
            this.Mass = Mass;
            this.Position = Position;
            this.Hp = Hp;
            this.MaxHp = MaxHp;
        }

        public Entity()
        {
            this.Position = new();
        }
    }
}
