// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Entity
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "mass")]
        public float Mass;
        [DataMember(Name = "position")]
        public DbVector2 Position;

        public Entity(
            int Id,
            float Mass,
            DbVector2 Position
        )
        {
            this.Id = Id;
            this.Mass = Mass;
            this.Position = Position;
        }

        public Entity()
        {
            this.Position = new();
        }
    }
}
