// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Player
    {
        [DataMember(Name = "Identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "player_id")]
        public int PlayerId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "dir")]
        public DbVector2 Dir;

        public Player(
            SpacetimeDB.Identity Identity,
            int PlayerId,
            string Name,
            DbVector2 Dir
        )
        {
            this.Identity = Identity;
            this.PlayerId = PlayerId;
            this.Name = Name;
            this.Dir = Dir;
        }

        public Player()
        {
            this.Name = "";
            this.Dir = new();
        }
    }
}
