// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SpeedBuff
    {
        [DataMember(Name = "player_id")]
        public int PlayerId;
        [DataMember(Name = "expire_at_ms")]
        public double ExpireAtMs;

        public SpeedBuff(
            int PlayerId,
            double ExpireAtMs
        )
        {
            this.PlayerId = PlayerId;
            this.ExpireAtMs = ExpireAtMs;
        }

        public SpeedBuff()
        {
        }
    }
}
