// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DebugDamageHandler(ReducerEventContext ctx, int entityId, float amount);
        public event DebugDamageHandler? OnDebugDamage;

        public void DebugDamage(int entityId, float amount)
        {
            conn.InternalCallReducer(new Reducer.DebugDamage(entityId, amount));
        }

        public bool InvokeDebugDamage(ReducerEventContext ctx, Reducer.DebugDamage args)
        {
            if (OnDebugDamage == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDebugDamage(
                ctx,
                args.EntityId,
                args.Amount
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DebugDamage : Reducer, IReducerArgs
        {
            [DataMember(Name = "entity_id")]
            public int EntityId;
            [DataMember(Name = "amount")]
            public float Amount;

            public DebugDamage(
                int EntityId,
                float Amount
            )
            {
                this.EntityId = EntityId;
                this.Amount = Amount;
            }

            public DebugDamage()
            {
            }

            string IReducerArgs.ReducerName => "DebugDamage";
        }
    }
}
