// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void FinishMergeHandler(ReducerEventContext ctx, int smallEntityId);
        public event FinishMergeHandler? OnFinishMerge;

        public void FinishMerge(int smallEntityId)
        {
            conn.InternalCallReducer(new Reducer.FinishMerge(smallEntityId));
        }

        public bool InvokeFinishMerge(ReducerEventContext ctx, Reducer.FinishMerge args)
        {
            if (OnFinishMerge == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnFinishMerge(
                ctx,
                args.SmallEntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class FinishMerge : Reducer, IReducerArgs
        {
            [DataMember(Name = "smallEntityId")]
            public int SmallEntityId;

            public FinishMerge(int SmallEntityId)
            {
                this.SmallEntityId = SmallEntityId;
            }

            public FinishMerge()
            {
            }

            string IReducerArgs.ReducerName => "FinishMerge";
        }
    }
}
