// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void Reducer1Handler(ReducerEventContext ctx);
        public event Reducer1Handler? OnReducer1;

        public void Reducer1()
        {
            conn.InternalCallReducer(new Reducer.Reducer1());
        }

        public bool InvokeReducer1(ReducerEventContext ctx, Reducer.Reducer1 args)
        {
            if (OnReducer1 == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnReducer1(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Reducer1 : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "Reducer1";
        }
    }
}
