// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SyncBallPosHandler(ReducerEventContext ctx, int entityId, SpacetimeDB.Types.DbVector2 newPos);
        public event SyncBallPosHandler? OnSyncBallPos;

        public void SyncBallPos(int entityId, SpacetimeDB.Types.DbVector2 newPos)
        {
            conn.InternalCallReducer(new Reducer.SyncBallPos(entityId, newPos));
        }

        public bool InvokeSyncBallPos(ReducerEventContext ctx, Reducer.SyncBallPos args)
        {
            if (OnSyncBallPos == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSyncBallPos(
                ctx,
                args.EntityId,
                args.NewPos
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SyncBallPos : Reducer, IReducerArgs
        {
            [DataMember(Name = "entity_id")]
            public int EntityId;
            [DataMember(Name = "new_pos")]
            public DbVector2 NewPos;

            public SyncBallPos(
                int EntityId,
                DbVector2 NewPos
            )
            {
                this.EntityId = EntityId;
                this.NewPos = NewPos;
            }

            public SyncBallPos()
            {
                this.NewPos = new();
            }

            string IReducerArgs.ReducerName => "SyncBallPos";
        }
    }
}
