// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerAmmo
    {
        [DataMember(Name = "player_id")]
        public int PlayerId;
        [DataMember(Name = "ammo_split")]
        public int AmmoSplit;

        public PlayerAmmo(
            int PlayerId,
            int AmmoSplit
        )
        {
            this.PlayerId = PlayerId;
            this.AmmoSplit = AmmoSplit;
        }

        public PlayerAmmo()
        {
        }
    }
}
