// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Shield
    {
        [DataMember(Name = "entity_id")]
        public int EntityId;
        [DataMember(Name = "shield_hp")]
        public float ShieldHp;
        [DataMember(Name = "shield_max")]
        public float ShieldMax;
        [DataMember(Name = "expire_at_ms")]
        public double ExpireAtMs;

        public Shield(
            int EntityId,
            float ShieldHp,
            float ShieldMax,
            double ExpireAtMs
        )
        {
            this.EntityId = EntityId;
            this.ShieldHp = ShieldHp;
            this.ShieldMax = ShieldMax;
            this.ExpireAtMs = ExpireAtMs;
        }

        public Shield()
        {
        }
    }
}
