// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SpawnFoodTimer
    {
        [DataMember(Name = "scheduled_id")]
        public ulong ScheduledId;
        [DataMember(Name = "schedule_at")]
        public SpacetimeDB.ScheduleAt ScheduleAt;

        public SpawnFoodTimer(
            ulong ScheduledId,
            SpacetimeDB.ScheduleAt ScheduleAt
        )
        {
            this.ScheduledId = ScheduledId;
            this.ScheduleAt = ScheduleAt;
        }

        public SpawnFoodTimer()
        {
            this.ScheduleAt = null!;
        }
    }
}
