// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BulletHandle : RemoteTableHandle<EventContext, Bullet>
        {
            protected override string RemoteTableName => "bullet";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(Bullet row) => row.EntityId;

                public EntityIdUniqueIndex(BulletHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal BulletHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(Bullet row) => row.EntityId;
        }

        public readonly BulletHandle Bullet;
    }

    public sealed class BulletCols
    {
        public global::SpacetimeDB.Col<Bullet, int> EntityId { get; }
        public global::SpacetimeDB.Col<Bullet, int> OwnerPlayerId { get; }
        public global::SpacetimeDB.Col<Bullet, float> DirX { get; }
        public global::SpacetimeDB.Col<Bullet, float> DirY { get; }
        public global::SpacetimeDB.Col<Bullet, double> SpawnedAtMs { get; }
        public global::SpacetimeDB.Col<Bullet, int> BulletType { get; }

        public BulletCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<Bullet, int>(tableName, "entity_id");
            OwnerPlayerId = new global::SpacetimeDB.Col<Bullet, int>(tableName, "owner_player_id");
            DirX = new global::SpacetimeDB.Col<Bullet, float>(tableName, "dir_x");
            DirY = new global::SpacetimeDB.Col<Bullet, float>(tableName, "dir_y");
            SpawnedAtMs = new global::SpacetimeDB.Col<Bullet, double>(tableName, "spawned_at_ms");
            BulletType = new global::SpacetimeDB.Col<Bullet, int>(tableName, "bullet_type");
        }
    }

    public sealed class BulletIxCols
    {
        public global::SpacetimeDB.IxCol<Bullet, int> EntityId { get; }

        public BulletIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<Bullet, int>(tableName, "entity_id");
        }
    }
}
