// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EntityHandle : RemoteTableHandle<EventContext, Entity>
        {
            protected override string RemoteTableName => "entity";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(Entity row) => row.Id;

                public IdUniqueIndex(EntityHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal EntityHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Entity row) => row.Id;
        }

        public readonly EntityHandle Entity;
    }

    public sealed class EntityCols
    {
        public global::SpacetimeDB.Col<Entity, int> Id { get; }
        public global::SpacetimeDB.Col<Entity, float> Mass { get; }
        public global::SpacetimeDB.Col<Entity, DbVector2> Position { get; }
        public global::SpacetimeDB.Col<Entity, float> Hp { get; }
        public global::SpacetimeDB.Col<Entity, float> MaxHp { get; }

        public EntityCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Entity, int>(tableName, "id");
            Mass = new global::SpacetimeDB.Col<Entity, float>(tableName, "mass");
            Position = new global::SpacetimeDB.Col<Entity, DbVector2>(tableName, "position");
            Hp = new global::SpacetimeDB.Col<Entity, float>(tableName, "hp");
            MaxHp = new global::SpacetimeDB.Col<Entity, float>(tableName, "max_hp");
        }
    }

    public sealed class EntityIxCols
    {
        public global::SpacetimeDB.IxCol<Entity, int> Id { get; }

        public EntityIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Entity, int>(tableName, "id");
        }
    }
}
