// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerAmmoHandle : RemoteTableHandle<EventContext, PlayerAmmo>
        {
            protected override string RemoteTableName => "player_ammo";

            public sealed class PlayerIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(PlayerAmmo row) => row.PlayerId;

                public PlayerIdUniqueIndex(PlayerAmmoHandle table) : base(table) { }
            }

            public readonly PlayerIdUniqueIndex PlayerId;

            internal PlayerAmmoHandle(DbConnection conn) : base(conn)
            {
                PlayerId = new(this);
            }

            protected override object GetPrimaryKey(PlayerAmmo row) => row.PlayerId;
        }

        public readonly PlayerAmmoHandle PlayerAmmo;
    }

    public sealed class PlayerAmmoCols
    {
        public global::SpacetimeDB.Col<PlayerAmmo, int> PlayerId { get; }
        public global::SpacetimeDB.Col<PlayerAmmo, int> AmmoSplit { get; }

        public PlayerAmmoCols(string tableName)
        {
            PlayerId = new global::SpacetimeDB.Col<PlayerAmmo, int>(tableName, "player_id");
            AmmoSplit = new global::SpacetimeDB.Col<PlayerAmmo, int>(tableName, "ammo_split");
        }
    }

    public sealed class PlayerAmmoIxCols
    {
        public global::SpacetimeDB.IxCol<PlayerAmmo, int> PlayerId { get; }

        public PlayerAmmoIxCols(string tableName)
        {
            PlayerId = new global::SpacetimeDB.IxCol<PlayerAmmo, int>(tableName, "player_id");
        }
    }
}
