// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ShieldHandle : RemoteTableHandle<EventContext, Shield>
        {
            protected override string RemoteTableName => "shield";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(Shield row) => row.EntityId;

                public EntityIdUniqueIndex(ShieldHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal ShieldHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(Shield row) => row.EntityId;
        }

        public readonly ShieldHandle Shield;
    }

    public sealed class ShieldCols
    {
        public global::SpacetimeDB.Col<Shield, int> EntityId { get; }
        public global::SpacetimeDB.Col<Shield, float> ShieldHp { get; }
        public global::SpacetimeDB.Col<Shield, float> ShieldMax { get; }
        public global::SpacetimeDB.Col<Shield, double> ExpireAtMs { get; }

        public ShieldCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<Shield, int>(tableName, "entity_id");
            ShieldHp = new global::SpacetimeDB.Col<Shield, float>(tableName, "shield_hp");
            ShieldMax = new global::SpacetimeDB.Col<Shield, float>(tableName, "shield_max");
            ExpireAtMs = new global::SpacetimeDB.Col<Shield, double>(tableName, "expire_at_ms");
        }
    }

    public sealed class ShieldIxCols
    {
        public global::SpacetimeDB.IxCol<Shield, int> EntityId { get; }

        public ShieldIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<Shield, int>(tableName, "entity_id");
        }
    }
}
