// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SpeedBuffHandle : RemoteTableHandle<EventContext, SpeedBuff>
        {
            protected override string RemoteTableName => "speed_buff";

            public sealed class PlayerIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(SpeedBuff row) => row.PlayerId;

                public PlayerIdUniqueIndex(SpeedBuffHandle table) : base(table) { }
            }

            public readonly PlayerIdUniqueIndex PlayerId;

            internal SpeedBuffHandle(DbConnection conn) : base(conn)
            {
                PlayerId = new(this);
            }

            protected override object GetPrimaryKey(SpeedBuff row) => row.PlayerId;
        }

        public readonly SpeedBuffHandle SpeedBuff;
    }

    public sealed class SpeedBuffCols
    {
        public global::SpacetimeDB.Col<SpeedBuff, int> PlayerId { get; }
        public global::SpacetimeDB.Col<SpeedBuff, double> ExpireAtMs { get; }

        public SpeedBuffCols(string tableName)
        {
            PlayerId = new global::SpacetimeDB.Col<SpeedBuff, int>(tableName, "player_id");
            ExpireAtMs = new global::SpacetimeDB.Col<SpeedBuff, double>(tableName, "expire_at_ms");
        }
    }

    public sealed class SpeedBuffIxCols
    {
        public global::SpacetimeDB.IxCol<SpeedBuff, int> PlayerId { get; }

        public SpeedBuffIxCols(string tableName)
        {
            PlayerId = new global::SpacetimeDB.IxCol<SpeedBuff, int>(tableName, "player_id");
        }
    }
}
