// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TestTableHandle : RemoteTableHandle<EventContext, TestTable>
        {
            protected override string RemoteTableName => "test_table";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(TestTable row) => row.Id;

                public IdUniqueIndex(TestTableHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal TestTableHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(TestTable row) => row.Id;
        }

        public readonly TestTableHandle TestTable;
    }

    public sealed class TestTableCols
    {
        public global::SpacetimeDB.Col<TestTable, int> Id { get; }
        public global::SpacetimeDB.Col<TestTable, string> Name { get; }

        public TestTableCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<TestTable, int>(tableName, "id");
            Name = new global::SpacetimeDB.Col<TestTable, string>(tableName, "name");
        }
    }

    public sealed class TestTableIxCols
    {
        public global::SpacetimeDB.IxCol<TestTable, int> Id { get; }

        public TestTableIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<TestTable, int>(tableName, "id");
        }
    }
}
